"""火山引擎 AI 图片翻译的轻量默认配置。"""

VOLCENGINE_IMAGE_DEFAULT_BASE_URL = "https://ark.cn-beijing.volces.com/api/v3"
VOLCENGINE_IMAGE_MODEL_HIGH_QUALITY = "doubao-seedream-5-0-pro-260628"
VOLCENGINE_IMAGE_MODEL_ECONOMY = "doubao-seedream-5-0-260128"
VOLCENGINE_IMAGE_DEFAULT_MODEL = VOLCENGINE_IMAGE_MODEL_HIGH_QUALITY

VOLCENGINE_IMAGE_MODEL_SUGGESTIONS = (
    VOLCENGINE_IMAGE_MODEL_HIGH_QUALITY,
    VOLCENGINE_IMAGE_MODEL_ECONOMY,
)


__all__ = [
    "VOLCENGINE_IMAGE_DEFAULT_BASE_URL",
    "VOLCENGINE_IMAGE_DEFAULT_MODEL",
    "VOLCENGINE_IMAGE_MODEL_ECONOMY",
    "VOLCENGINE_IMAGE_MODEL_HIGH_QUALITY",
    "VOLCENGINE_IMAGE_MODEL_SUGGESTIONS",
]
