#!/usr/bin/env python3
"""Generate platform-specific, hash-checked release dependency locks.

Run this script for each supported release target. It invokes ``uv pip
compile`` with the target Python version and platform, so a lock named
``*-win-py310`` is not accidentally generated by the developer's current
interpreter.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK_TARGETS = {
    "text-win-py310": (
        "requirements.txt",
        "requirements-text-win-py310.lock.txt",
        "3.10",
        "windows",
    ),
    "text-win-py311": (
        "requirements.txt",
        "requirements-text-win-py311.lock.txt",
        "3.11",
        "windows",
    ),
    "text-macos-py311": (
        "requirements.txt",
        "requirements-text-macos-py311.lock.txt",
        "3.11",
        "macos",
    ),
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target", choices=sorted(LOCK_TARGETS))
    args = parser.parse_args()

    uv = shutil.which("uv")
    if uv is None:
        raise SystemExit("Install uv first: https://docs.astral.sh/uv/")

    source, output, python_version, platform = LOCK_TARGETS[args.target]
    subprocess.run(
        [
            uv,
            "pip",
            "compile",
            "--generate-hashes",
            "--python-version",
            python_version,
            "--python-platform",
            platform,
            "--output-file",
            output,
            source,
        ],
        cwd=ROOT,
        check=True,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
